<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\SiteContent;

class HomePageContentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $contentItems = [
            // Hero Section
            [
                'key' => 'hero_title',
                'title' => 'Hero Section Title',
                'content' => 'Welcome to Amako Momo Shop',
                'type' => 'text',
                'section' => 'home',
                'component' => 'hero',
                'platform' => 'all',
                'description' => 'Main title for the hero section',
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'key' => 'hero_subtitle',
                'title' => 'Hero Section Subtitle',
                'content' => 'Authentic Nepalese Momos - Fresh, Delicious, and Made with Love',
                'type' => 'text',
                'section' => 'home',
                'component' => 'hero',
                'platform' => 'all',
                'description' => 'Subtitle for the hero section',
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'key' => 'hero_cta_text',
                'title' => 'Hero CTA Button Text',
                'content' => 'Order Now',
                'type' => 'text',
                'section' => 'home',
                'component' => 'hero',
                'platform' => 'all',
                'description' => 'Call-to-action button text',
                'is_active' => true,
                'sort_order' => 3,
            ],

            // Featured Products Section
            [
                'key' => 'featured_products_title',
                'title' => 'Featured Products Title',
                'content' => '🌟 Featured Products',
                'type' => 'text',
                'section' => 'home',
                'component' => 'featured',
                'platform' => 'all',
                'description' => 'Title for the featured products section',
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'key' => 'featured_products_description',
                'title' => 'Featured Products Description',
                'content' => 'Discover our handpicked selection of premium products — handpicked for you.',
                'type' => 'text',
                'section' => 'home',
                'component' => 'featured',
                'platform' => 'all',
                'description' => 'Description for the featured products section',
                'is_active' => true,
                'sort_order' => 5,
            ],

            // Why Choose Us Section
            [
                'key' => 'why_choose_title',
                'title' => 'Why Choose Us Title',
                'content' => '✨ Why Choose Amako Shop?',
                'type' => 'text',
                'section' => 'home',
                'component' => 'why-choose',
                'platform' => 'all',
                'description' => 'Title for the why choose us section',
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'key' => 'why_choose_description',
                'title' => 'Why Choose Us Description',
                'content' => 'From our kitchen to your heart — here\'s why thousands trust us with their favorite comfort food.',
                'type' => 'text',
                'section' => 'home',
                'component' => 'why-choose',
                'platform' => 'all',
                'description' => 'Description for the why choose us section',
                'is_active' => true,
                'sort_order' => 7,
            ],

            // Statistics Section
            [
                'key' => 'stats_orders_count',
                'title' => 'Orders Delivered Count',
                'content' => '197+',
                'type' => 'text',
                'section' => 'home',
                'component' => 'stats',
                'platform' => 'all',
                'description' => 'Number of orders delivered',
                'is_active' => true,
                'sort_order' => 8,
            ],
            [
                'key' => 'stats_orders_label',
                'title' => 'Orders Delivered Label',
                'content' => 'Orders Delivered',
                'type' => 'text',
                'section' => 'home',
                'component' => 'stats',
                'platform' => 'all',
                'description' => 'Label for orders delivered',
                'is_active' => true,
                'sort_order' => 9,
            ],
            [
                'key' => 'stats_orders_growth',
                'title' => 'Orders Growth',
                'content' => '📈 +15% this month',
                'type' => 'text',
                'section' => 'home',
                'component' => 'stats',
                'platform' => 'all',
                'description' => 'Growth percentage for orders',
                'is_active' => true,
                'sort_order' => 10,
            ],
            [
                'key' => 'stats_customers_count',
                'title' => 'Happy Customers Count',
                'content' => '19+',
                'type' => 'text',
                'section' => 'home',
                'component' => 'stats',
                'platform' => 'all',
                'description' => 'Number of happy customers',
                'is_active' => true,
                'sort_order' => 11,
            ],
            [
                'key' => 'stats_customers_label',
                'title' => 'Happy Customers Label',
                'content' => 'Happy Customers',
                'type' => 'text',
                'section' => 'home',
                'component' => 'stats',
                'platform' => 'all',
                'description' => 'Label for happy customers',
                'is_active' => true,
                'sort_order' => 12,
            ],
            [
                'key' => 'stats_customers_satisfaction',
                'title' => 'Customer Satisfaction',
                'content' => '😊 100% satisfaction',
                'type' => 'text',
                'section' => 'home',
                'component' => 'stats',
                'platform' => 'all',
                'description' => 'Customer satisfaction rate',
                'is_active' => true,
                'sort_order' => 13,
            ],
            [
                'key' => 'stats_years_count',
                'title' => 'Years in Business Count',
                'content' => '1+',
                'type' => 'text',
                'section' => 'home',
                'component' => 'stats',
                'platform' => 'all',
                'description' => 'Number of years in business',
                'is_active' => true,
                'sort_order' => 14,
            ],
            [
                'key' => 'stats_years_label',
                'title' => 'Years in Business Label',
                'content' => 'Years in Business',
                'type' => 'text',
                'section' => 'home',
                'component' => 'stats',
                'platform' => 'all',
                'description' => 'Label for years in business',
                'is_active' => true,
                'sort_order' => 15,
            ],
            [
                'key' => 'stats_years_badge',
                'title' => 'Years in Business Badge',
                'content' => '🏆 Trusted brand',
                'type' => 'text',
                'section' => 'home',
                'component' => 'stats',
                'platform' => 'all',
                'description' => 'Badge for years in business',
                'is_active' => true,
                'sort_order' => 16,
            ],
            [
                'key' => 'stats_varieties_count',
                'title' => 'Momo Varieties Count',
                'content' => '21+',
                'type' => 'text',
                'section' => 'home',
                'component' => 'stats',
                'platform' => 'all',
                'description' => 'Number of momo varieties',
                'is_active' => true,
                'sort_order' => 17,
            ],
            [
                'key' => 'stats_varieties_label',
                'title' => 'Momo Varieties Label',
                'content' => 'Momo Varieties',
                'type' => 'text',
                'section' => 'home',
                'component' => 'stats',
                'platform' => 'all',
                'description' => 'Label for momo varieties',
                'is_active' => true,
                'sort_order' => 18,
            ],
            [
                'key' => 'stats_varieties_badge',
                'title' => 'Momo Varieties Badge',
                'content' => '🥟 Unique flavors',
                'type' => 'text',
                'section' => 'home',
                'component' => 'stats',
                'platform' => 'all',
                'description' => 'Badge for momo varieties',
                'is_active' => true,
                'sort_order' => 19,
            ],

            // Features Section
            [
                'key' => 'feature_fresh_ingredients_icon',
                'title' => 'Fresh Ingredients Icon',
                'content' => '🥬',
                'type' => 'text',
                'section' => 'home',
                'component' => 'features',
                'platform' => 'all',
                'description' => 'Icon for fresh ingredients feature',
                'is_active' => true,
                'sort_order' => 20,
            ],
            [
                'key' => 'feature_fresh_ingredients_title',
                'title' => 'Fresh Ingredients Title',
                'content' => 'Fresh Ingredients',
                'type' => 'text',
                'section' => 'home',
                'component' => 'features',
                'platform' => 'all',
                'description' => 'Title for fresh ingredients feature',
                'is_active' => true,
                'sort_order' => 21,
            ],
            [
                'key' => 'feature_fresh_ingredients_description',
                'title' => 'Fresh Ingredients Description',
                'content' => 'Fresh, high-quality ingredients sourced daily from local markets.',
                'type' => 'text',
                'section' => 'home',
                'component' => 'features',
                'platform' => 'all',
                'description' => 'Description for fresh ingredients feature',
                'is_active' => true,
                'sort_order' => 22,
            ],
            [
                'key' => 'feature_authentic_recipes_icon',
                'title' => 'Authentic Recipes Icon',
                'content' => '👩‍🍳',
                'type' => 'text',
                'section' => 'home',
                'component' => 'features',
                'platform' => 'all',
                'description' => 'Icon for authentic recipes feature',
                'is_active' => true,
                'sort_order' => 23,
            ],
            [
                'key' => 'feature_authentic_recipes_title',
                'title' => 'Authentic Recipes Title',
                'content' => 'Authentic Recipes',
                'type' => 'text',
                'section' => 'home',
                'component' => 'features',
                'platform' => 'all',
                'description' => 'Title for authentic recipes feature',
                'is_active' => true,
                'sort_order' => 24,
            ],
            [
                'key' => 'feature_authentic_recipes_description',
                'title' => 'Authentic Recipes Description',
                'content' => 'Traditional Nepalese recipes passed down through generations.',
                'type' => 'text',
                'section' => 'home',
                'component' => 'features',
                'platform' => 'all',
                'description' => 'Description for authentic recipes feature',
                'is_active' => true,
                'sort_order' => 25,
            ],
            [
                'key' => 'feature_fast_delivery_icon',
                'title' => 'Fast Delivery Icon',
                'content' => '🚚',
                'type' => 'text',
                'section' => 'home',
                'component' => 'features',
                'platform' => 'all',
                'description' => 'Icon for fast delivery feature',
                'is_active' => true,
                'sort_order' => 26,
            ],
            [
                'key' => 'feature_fast_delivery_title',
                'title' => 'Fast Delivery Title',
                'content' => 'Fast Delivery',
                'type' => 'text',
                'section' => 'home',
                'component' => 'features',
                'platform' => 'all',
                'description' => 'Title for fast delivery feature',
                'is_active' => true,
                'sort_order' => 27,
            ],
            [
                'key' => 'feature_fast_delivery_description',
                'title' => 'Fast Delivery Description',
                'content' => 'Average delivery time: 25 minutes. Hot and fresh!',
                'type' => 'text',
                'section' => 'home',
                'component' => 'features',
                'platform' => 'all',
                'description' => 'Description for fast delivery feature',
                'is_active' => true,
                'sort_order' => 28,
            ],
            [
                'key' => 'feature_quality_assured_title',
                'title' => 'Quality Assured Title',
                'content' => 'Quality Assured',
                'type' => 'text',
                'section' => 'home',
                'component' => 'features',
                'platform' => 'all',
                'description' => 'Title for quality assured feature',
                'is_active' => true,
                'sort_order' => 29,
            ],
            [
                'key' => 'feature_quality_assured_description',
                'title' => 'Quality Assured Description',
                'content' => 'Every order carefully prepared and quality-checked.',
                'type' => 'text',
                'section' => 'home',
                'component' => 'features',
                'platform' => 'all',
                'description' => 'Description for quality assured feature',
                'is_active' => true,
                'sort_order' => 30,
            ],
            [
                'key' => 'feature_support_icon',
                'title' => '24/7 Support Icon',
                'content' => '🎧',
                'type' => 'text',
                'section' => 'home',
                'component' => 'features',
                'platform' => 'all',
                'description' => 'Icon for 24/7 support feature',
                'is_active' => true,
                'sort_order' => 31,
            ],
            [
                'key' => 'feature_support_title',
                'title' => '24/7 Support Title',
                'content' => '24/7 Support',
                'type' => 'text',
                'section' => 'home',
                'component' => 'features',
                'platform' => 'all',
                'description' => 'Title for 24/7 support feature',
                'is_active' => true,
                'sort_order' => 32,
            ],
            [
                'key' => 'feature_support_description',
                'title' => '24/7 Support Description',
                'content' => 'Our support team always ready to help you.',
                'type' => 'text',
                'section' => 'home',
                'component' => 'features',
                'platform' => 'all',
                'description' => 'Description for 24/7 support feature',
                'is_active' => true,
                'sort_order' => 33,
            ],
            [
                'key' => 'feature_value_icon',
                'title' => 'Great Value Icon',
                'content' => '💰',
                'type' => 'text',
                'section' => 'home',
                'component' => 'features',
                'platform' => 'all',
                'description' => 'Icon for great value feature',
                'is_active' => true,
                'sort_order' => 34,
            ],
            [
                'key' => 'feature_value_title',
                'title' => 'Great Value Title',
                'content' => 'Great Value',
                'type' => 'text',
                'section' => 'home',
                'component' => 'features',
                'platform' => 'all',
                'description' => 'Title for great value feature',
                'is_active' => true,
                'sort_order' => 35,
            ],
            [
                'key' => 'feature_value_description',
                'title' => 'Great Value Description',
                'content' => 'Delicious momos at affordable prices with combo deals.',
                'type' => 'text',
                'section' => 'home',
                'component' => 'features',
                'platform' => 'all',
                'description' => 'Description for great value feature',
                'is_active' => true,
                'sort_order' => 36,
            ],

            // CTA Section
            [
                'key' => 'cta_title',
                'title' => 'CTA Section Title',
                'content' => 'Try Our Momos Today',
                'type' => 'text',
                'section' => 'home',
                'component' => 'cta',
                'platform' => 'all',
                'description' => 'Title for the call-to-action section',
                'is_active' => true,
                'sort_order' => 37,
            ],

            // Reviews Section
            [
                'key' => 'reviews_title',
                'title' => 'Customer Reviews Title',
                'content' => '💬 Customer Reviews',
                'type' => 'text',
                'section' => 'home',
                'component' => 'reviews',
                'platform' => 'all',
                'description' => 'Title for the customer reviews section',
                'is_active' => true,
                'sort_order' => 38,
            ],
            [
                'key' => 'reviews_subtitle',
                'title' => 'Customer Reviews Subtitle',
                'content' => 'See what our happy customers are saying about us',
                'type' => 'text',
                'section' => 'home',
                'component' => 'reviews',
                'platform' => 'all',
                'description' => 'Subtitle for the customer reviews section',
                'is_active' => true,
                'sort_order' => 39,
            ],

            // Contact Information Section
            [
                'key' => 'contact_title',
                'title' => 'Contact Section Title',
                'content' => '📍 Visit Us',
                'type' => 'text',
                'section' => 'home',
                'component' => 'contact-info',
                'platform' => 'all',
                'description' => 'Title for the contact section',
                'is_active' => true,
                'sort_order' => 40,
            ],
            [
                'key' => 'contact_subtitle',
                'title' => 'Contact Section Subtitle',
                'content' => 'Find us and get in touch',
                'type' => 'text',
                'section' => 'home',
                'component' => 'contact-info',
                'platform' => 'all',
                'description' => 'Subtitle for the contact section',
                'is_active' => true,
                'sort_order' => 41,
            ],
            [
                'key' => 'business_hours_title',
                'title' => 'Business Hours Title',
                'content' => '🕒 Business Hours',
                'type' => 'text',
                'section' => 'home',
                'component' => 'contact-info',
                'platform' => 'all',
                'description' => 'Title for business hours',
                'is_active' => true,
                'sort_order' => 42,
            ],
            [
                'key' => 'business_hours_text',
                'title' => 'Business Hours Text',
                'content' => 'Open 7 days a week<br>10:00 AM - 9:00 PM',
                'type' => 'html',
                'section' => 'home',
                'component' => 'contact-info',
                'platform' => 'all',
                'description' => 'Business hours text',
                'is_active' => true,
                'sort_order' => 43,
            ],
            [
                'key' => 'business_status',
                'title' => 'Business Status',
                'content' => '🟢 Currently Open',
                'type' => 'text',
                'section' => 'home',
                'component' => 'contact-info',
                'platform' => 'all',
                'description' => 'Current business status',
                'is_active' => true,
                'sort_order' => 44,
            ],
            [
                'key' => 'location_title',
                'title' => 'Location Title',
                'content' => '🗺️ Find Us on the Map',
                'type' => 'text',
                'section' => 'home',
                'component' => 'contact-info',
                'platform' => 'all',
                'description' => 'Title for location section',
                'is_active' => true,
                'sort_order' => 45,
            ],
            [
                'key' => 'restaurant_name',
                'title' => 'Restaurant Name',
                'content' => '📍 Amako Momo Restaurant',
                'type' => 'text',
                'section' => 'home',
                'component' => 'contact-info',
                'platform' => 'all',
                'description' => 'Restaurant name and location',
                'is_active' => true,
                'sort_order' => 46,
            ],
            [
                'key' => 'restaurant_address',
                'title' => 'Restaurant Address',
                'content' => 'Thamel, Kathmandu, Nepal',
                'type' => 'text',
                'section' => 'home',
                'component' => 'contact-info',
                'platform' => 'all',
                'description' => 'Restaurant address',
                'is_active' => true,
                'sort_order' => 47,
            ],
            [
                'key' => 'get_directions_text',
                'title' => 'Get Directions Text',
                'content' => '📍 Get Directions',
                'type' => 'text',
                'section' => 'home',
                'component' => 'contact-info',
                'platform' => 'all',
                'description' => 'Get directions button text',
                'is_active' => true,
                'sort_order' => 48,
            ],
            [
                'key' => 'copy_address_text',
                'title' => 'Copy Address Text',
                'content' => '📋 Copy Address',
                'type' => 'text',
                'section' => 'home',
                'component' => 'contact-info',
                'platform' => 'all',
                'description' => 'Copy address button text',
                'is_active' => true,
                'sort_order' => 49,
            ],
            [
                'key' => 'follow_us_title',
                'title' => 'Follow Us Title',
                'content' => 'Follow Us',
                'type' => 'text',
                'section' => 'home',
                'component' => 'contact-info',
                'platform' => 'all',
                'description' => 'Title for follow us section',
                'is_active' => true,
                'sort_order' => 50,
            ],
            [
                'key' => 'follow_us_description',
                'title' => 'Follow Us Description',
                'content' => 'Stay updated with our latest offers and behind-the-scenes content',
                'type' => 'text',
                'section' => 'home',
                'component' => 'contact-info',
                'platform' => 'all',
                'description' => 'Description for follow us section',
                'is_active' => true,
                'sort_order' => 51,
            ],
            [
                'key' => 'contact_info_title',
                'title' => 'Contact Information Title',
                'content' => '📞 Contact Information',
                'type' => 'text',
                'section' => 'home',
                'component' => 'contact-info',
                'platform' => 'all',
                'description' => 'Title for contact information',
                'is_active' => true,
                'sort_order' => 52,
            ],
            [
                'key' => 'phone_number',
                'title' => 'Phone Number',
                'content' => '+1 (555) 123-4567',
                'type' => 'text',
                'section' => 'home',
                'component' => 'contact-info',
                'platform' => 'all',
                'description' => 'Phone number',
                'is_active' => true,
                'sort_order' => 53,
            ],
            [
                'key' => 'email_address',
                'title' => 'Email Address',
                'content' => 'info@amakoshop.com',
                'type' => 'text',
                'section' => 'home',
                'component' => 'contact-info',
                'platform' => 'all',
                'description' => 'Email address',
                'is_active' => true,
                'sort_order' => 54,
            ],
            [
                'key' => 'contact_help_text',
                'title' => 'Contact Help Text',
                'content' => 'Need help? We\'re here to assist you!',
                'type' => 'text',
                'section' => 'home',
                'component' => 'contact-info',
                'platform' => 'all',
                'description' => 'Help text for contact section',
                'is_active' => true,
                'sort_order' => 55,
            ],
            [
                'key' => 'call_now_text',
                'title' => 'Call Now Text',
                'content' => 'Call Now',
                'type' => 'text',
                'section' => 'home',
                'component' => 'contact-info',
                'platform' => 'all',
                'description' => 'Call now button text',
                'is_active' => true,
                'sort_order' => 56,
            ],
            [
                'key' => 'email_text',
                'title' => 'Email Text',
                'content' => 'Email',
                'type' => 'text',
                'section' => 'home',
                'component' => 'contact-info',
                'platform' => 'all',
                'description' => 'Email button text',
                'is_active' => true,
                'sort_order' => 57,
            ],
            [
                'key' => 'chat_text',
                'title' => 'Chat Text',
                'content' => 'Chat',
                'type' => 'text',
                'section' => 'home',
                'component' => 'contact-info',
                'platform' => 'all',
                'description' => 'Chat button text',
                'is_active' => true,
                'sort_order' => 58,
            ],
        ];

        foreach ($contentItems as $item) {
            SiteContent::updateOrCreate(
                ['key' => $item['key']],
                $item
            );
        }
    }
}
