@extends('layouts.app')

@section('title', 'Interactive Tour - Welcome to AmaKo!')

@section('content')
<!-- Interactive Tour Overlay -->
<div id="tour-overlay" class="fixed inset-0 z-50 bg-black bg-opacity-50 hidden">
    <!-- Blurred Background -->
    <div class="absolute inset-0 backdrop-blur-sm"></div>
    
    <!-- Tour Content -->
    <div class="relative h-full flex items-center justify-center">
        <!-- Interactive Mascot Character -->
        <div id="tour-mascot" class="absolute bottom-8 right-8 z-10 group">
            <!-- Animated Mascot Circle -->
            <div class="bg-gradient-to-br from-[#6E0D25] to-[#8B0D2F] rounded-full p-6 shadow-2xl border-4 border-white transform transition-all duration-300 hover:scale-110 hover:rotate-12 animate-bounce">
                <div class="text-5xl group-hover:scale-125 transition-transform duration-300">🥟</div>
            </div>
            
            <!-- Floating particles around mascot -->
            <div class="absolute -top-2 -right-2 w-4 h-4 bg-yellow-400 rounded-full animate-ping"></div>
            <div class="absolute -bottom-2 -left-2 w-3 h-3 bg-pink-400 rounded-full animate-pulse"></div>
            <div class="absolute top-1/2 -right-6 w-2 h-2 bg-blue-400 rounded-full animate-bounce"></div>
            
            <!-- Interactive Speech Bubble -->
            <div id="tour-speech" class="absolute bottom-full right-0 mb-4 bg-gradient-to-br from-white to-gray-50 rounded-2xl p-6 shadow-2xl max-w-xs border-2 border-[#6E0D25] transform transition-all duration-300 hover:scale-105">
                <div class="text-sm font-bold text-[#6E0D25] mb-2 flex items-center">
                    <span class="text-lg mr-2">🎯</span>
                    AmaKo Guide
                </div>
                <div id="tour-message" class="text-gray-700 text-sm leading-relaxed">Welcome! Let's explore AmaKo together!</div>
                <!-- Animated speech bubble tail -->
                <div class="absolute top-full right-6 w-0 h-0 border-l-8 border-r-8 border-t-8 border-transparent border-t-white transform rotate-45"></div>
                <!-- Glow effect -->
                <div class="absolute inset-0 bg-gradient-to-br from-[#6E0D25] to-[#8B0D2F] rounded-2xl opacity-10 blur-sm"></div>
            </div>
        </div>
        
        <!-- Interactive Tour Navigation -->
        <div class="absolute bottom-6 left-1/2 transform -translate-x-1/2 flex space-x-3">
            <button id="tour-prev" onclick="previousTourStep()" class="group bg-gradient-to-r from-[#6E0D25] to-[#8B0D2F] text-white px-6 py-3 rounded-full hover:from-[#8B0D2F] hover:to-[#6E0D25] transition-all duration-200 shadow-lg transform hover:scale-105 hover:-rotate-2">
                <span class="flex items-center">
                    <span class="text-lg mr-1">←</span>
                    Previous
                </span>
            </button>
            <button id="tour-next" onclick="nextTourStep()" class="group bg-gradient-to-r from-[#6E0D25] to-[#8B0D2F] text-white px-6 py-3 rounded-full hover:from-[#8B0D2F] hover:to-[#6E0D25] transition-all duration-200 shadow-lg transform hover:scale-105 hover:rotate-2">
                <span class="flex items-center">
                    Next
                    <span class="text-lg ml-1">→</span>
                </span>
            </button>
            <button id="tour-skip" onclick="skipTour()" class="group bg-gradient-to-r from-gray-500 to-gray-600 text-white px-6 py-3 rounded-full hover:from-gray-600 hover:to-gray-500 transition-all duration-200 shadow-lg transform hover:scale-105">
                <span class="flex items-center">
                    <span class="text-lg mr-1">⏭️</span>
                    Skip Tour
                </span>
            </button>
        </div>
        
        <!-- Interactive Progress Indicator -->
        <div class="absolute top-6 left-1/2 transform -translate-x-1/2">
            <div id="tour-progress" class="flex space-x-2 bg-white bg-opacity-90 rounded-full p-2 shadow-lg">
                <!-- Progress dots will be generated by JavaScript -->
            </div>
        </div>
    </div>
</div>

<!-- Interactive Focus Highlight -->
<div id="tour-highlight" class="fixed z-40 pointer-events-none hidden">
    <div class="absolute inset-0 bg-gradient-to-r from-[#6E0D25] to-[#8B0D2F] bg-opacity-20 rounded-xl border-4 border-[#6E0D25] shadow-2xl animate-pulse"></div>
    <!-- Animated corner indicators -->
    <div class="absolute -top-2 -left-2 w-4 h-4 bg-[#6E0D25] rounded-full animate-ping"></div>
    <div class="absolute -top-2 -right-2 w-4 h-4 bg-[#6E0D25] rounded-full animate-ping" style="animation-delay: 0.5s;"></div>
    <div class="absolute -bottom-2 -left-2 w-4 h-4 bg-[#6E0D25] rounded-full animate-ping" style="animation-delay: 1s;"></div>
    <div class="absolute -bottom-2 -right-2 w-4 h-4 bg-[#6E0D25] rounded-full animate-ping" style="animation-delay: 1.5s;"></div>
</div>

<!-- Tour Steps Data -->
<script>
const tourSteps = [
    {
        id: 'welcome',
        target: null,
        message: "Hi! I'm AmaKo, your friendly guide! 🥟 Let's explore how to order delicious momos together!",
        position: 'center'
    },
    {
        id: 'menu-button',
        target: 'a[href*="menu"]',
        message: "First, let's look at the menu! Click the 'Menu' button to see all our delicious momos and more!",
        position: 'bottom-right'
    },
    {
        id: 'home-button',
        target: 'a[href*="home"]',
        message: "This is your home page - where you'll find featured items and special offers!",
        position: 'bottom-right'
    },
    {
        id: 'cart-button',
        target: '.cart-icon, [data-cart]',
        message: "When you add items to your cart, you'll see them here! Click to view your order.",
        position: 'bottom-right'
    },
    {
        id: 'search',
        target: 'input[type="search"], .search-input',
        message: "Can't find what you're looking for? Use the search bar to find specific items quickly!",
        position: 'bottom-right'
    },
    {
        id: 'gps-location',
        target: '.location-button, [data-location]',
        message: "Set your location for accurate delivery times! GPS helps us find the nearest branch.",
        position: 'bottom-right'
    },
    {
        id: 'account',
        target: 'a[href*="profile"], .user-menu',
        message: "Create an account to track orders, earn rewards, and save your favorite items!",
        position: 'bottom-right'
    },
    {
        id: 'help',
        target: 'a[href*="help"]',
        message: "Need help? Click here anytime for support and guides!",
        position: 'bottom-right'
    },
    {
        id: 'ordering-process',
        target: '.product-card, .add-to-cart',
        message: "See something you like? Click 'Add to Cart' to start your order!",
        position: 'bottom-right'
    },
    {
        id: 'checkout',
        target: 'a[href*="checkout"], .checkout-button',
        message: "Ready to order? Click here to review your cart and complete your purchase!",
        position: 'bottom-right'
    },
    {
        id: 'payment',
        target: '.payment-methods, [data-payment]',
        message: "We accept cash, cards, and digital wallets. All payments are secure!",
        position: 'bottom-right'
    },
    {
        id: 'tracking',
        target: '.order-status, [data-tracking]',
        message: "Track your order in real-time! We'll keep you updated every step of the way.",
        position: 'bottom-right'
    },
    {
        id: 'rewards',
        target: '.badge-system, [data-rewards]',
        message: "Earn points with every order! Unlock badges and exclusive rewards!",
        position: 'bottom-right'
    },
    {
        id: 'completion',
        target: null,
        message: "You're all set! 🎉 You now know how to use AmaKo. Start ordering and enjoy delicious momos!",
        position: 'center'
    }
];

let currentStep = 0;
let tourActive = false;

// Initialize tour
function initTour() {
    tourActive = true;
    currentStep = 0;
    showTourStep();
    document.getElementById('tour-overlay').classList.remove('hidden');
    document.body.style.overflow = 'hidden';
}

// Show current tour step
function showTourStep() {
    const step = tourSteps[currentStep];
    const mascot = document.getElementById('tour-mascot');
    const message = document.getElementById('tour-message');
    const highlight = document.getElementById('tour-highlight');
    
    // Update message
    message.textContent = step.message;
    
    // Update progress
    updateProgress();
    
    // Handle target element
    if (step.target) {
        const targetElement = document.querySelector(step.target);
        if (targetElement) {
            highlightElement(targetElement);
            positionMascot(targetElement, step.position);
        } else {
            // If target not found, position mascot in center
            positionMascot(null, 'center');
            highlight.style.display = 'none';
        }
    } else {
        // No target (welcome/completion steps)
        positionMascot(null, 'center');
        highlight.style.display = 'none';
    }
    
    // Update navigation buttons
    updateNavigationButtons();
}

// Highlight target element
function highlightElement(element) {
    const highlight = document.getElementById('tour-highlight');
    const rect = element.getBoundingClientRect();
    
    highlight.style.display = 'block';
    highlight.style.left = (rect.left - 12) + 'px';
    highlight.style.top = (rect.top - 12) + 'px';
    highlight.style.width = (rect.width + 24) + 'px';
    highlight.style.height = (rect.height + 24) + 'px';
    
    // Add smooth animation
    highlight.style.transition = 'all 0.3s ease-in-out';
    
    // Make element clickable and add glow effect
    element.style.zIndex = '60';
    element.style.position = 'relative';
    element.style.boxShadow = '0 0 20px rgba(110, 13, 37, 0.5)';
    element.style.borderRadius = '8px';
    
    // Add pulse animation to the element
    element.style.animation = 'pulse-glow 2s ease-in-out infinite';
}

// Position mascot relative to target
function positionMascot(element, position) {
    const mascot = document.getElementById('tour-mascot');
    const speech = document.getElementById('tour-speech');
    
    if (element && position !== 'center') {
        const rect = element.getBoundingClientRect();
        const windowWidth = window.innerWidth;
        const windowHeight = window.innerHeight;
        const mascotWidth = 120; // Approximate mascot width
        const mascotHeight = 120; // Approximate mascot height
        const speechWidth = 250; // Approximate speech bubble width
        const speechHeight = 100; // Approximate speech bubble height
        
        let left, top;
        
        switch (position) {
            case 'bottom-right':
                // Position mascot to the right and below the target
                left = Math.min(rect.right + 30, windowWidth - mascotWidth - 20);
                top = Math.min(rect.bottom + 30, windowHeight - mascotHeight - 20);
                break;
            case 'bottom-left':
                // Position mascot to the left and below the target
                left = Math.max(rect.left - speechWidth - 30, 20);
                top = Math.min(rect.bottom + 30, windowHeight - mascotHeight - 20);
                break;
            case 'top-right':
                // Position mascot to the right and above the target
                left = Math.min(rect.right + 30, windowWidth - mascotWidth - 20);
                top = Math.max(rect.top - speechHeight - 30, 20);
                break;
            case 'top-left':
                // Position mascot to the left and above the target
                left = Math.max(rect.left - speechWidth - 30, 20);
                top = Math.max(rect.top - speechHeight - 30, 20);
                break;
        }
        
        // Ensure mascot stays within viewport bounds
        left = Math.max(20, Math.min(left, windowWidth - mascotWidth - 20));
        top = Math.max(20, Math.min(top, windowHeight - mascotHeight - 20));
        
        mascot.style.left = left + 'px';
        mascot.style.top = top + 'px';
        mascot.style.right = 'auto';
        mascot.style.bottom = 'auto';
        mascot.style.transform = 'none';
        
        // Add smooth animation
        mascot.style.transition = 'all 0.5s ease-in-out';
    } else {
        // Center position for welcome/completion steps
        mascot.style.left = '50%';
        mascot.style.top = '50%';
        mascot.style.transform = 'translate(-50%, -50%)';
        mascot.style.right = 'auto';
        mascot.style.bottom = 'auto';
        mascot.style.transition = 'all 0.5s ease-in-out';
    }
}

// Update progress indicator
function updateProgress() {
    const progress = document.getElementById('tour-progress');
    progress.innerHTML = '';
    
    tourSteps.forEach((step, index) => {
        const dot = document.createElement('div');
        const isActive = index === currentStep;
        const isCompleted = index < currentStep;
        
        dot.className = `w-4 h-4 rounded-full transition-all duration-300 transform hover:scale-125 cursor-pointer ${
            isActive ? 'bg-[#6E0D25] shadow-lg scale-125' : 
            isCompleted ? 'bg-green-500' : 'bg-gray-300'
        }`;
        
        // Add click functionality to jump to specific step
        dot.addEventListener('click', () => {
            currentStep = index;
            showTourStep();
        });
        
        // Add tooltip
        dot.title = `Step ${index + 1}: ${step.id}`;
        
        progress.appendChild(dot);
    });
}

// Update navigation buttons
function updateNavigationButtons() {
    const prevBtn = document.getElementById('tour-prev');
    const nextBtn = document.getElementById('tour-next');
    
    prevBtn.disabled = currentStep === 0;
    nextBtn.textContent = currentStep === tourSteps.length - 1 ? 'Finish' : 'Next →';
    
    prevBtn.style.opacity = currentStep === 0 ? '0.5' : '1';
}

// Navigation functions
function nextTourStep() {
    if (currentStep < tourSteps.length - 1) {
        currentStep++;
        showTourStep();
    } else {
        completeTour();
    }
}

function previousTourStep() {
    if (currentStep > 0) {
        currentStep--;
        showTourStep();
    }
}

function skipTour() {
    completeTour();
}

function completeTour() {
    tourActive = false;
    document.getElementById('tour-overlay').classList.add('hidden');
    document.getElementById('tour-highlight').style.display = 'none';
    document.body.style.overflow = '';
    
    // Show completion message
    showToast('Tour completed! You\'re ready to start ordering! 🎉', 'success');
    
    // Save tour completion to localStorage
    localStorage.setItem('amako-tour-completed', 'true');
}

// Toast notification function
function showToast(message, type = 'info') {
    const toast = document.createElement('div');
    toast.className = `fixed top-4 right-4 px-6 py-3 rounded-lg text-white ${
        type === 'success' ? 'bg-green-500' : type === 'error' ? 'bg-red-500' : 'bg-blue-500'
    } shadow-lg z-50 transform transition-all duration-300 ease-in-out`;
    toast.textContent = message;
    document.body.appendChild(toast);
    
    setTimeout(() => {
        toast.remove();
    }, 3000);
}

// Function to start tour manually
function startAmaKoTour() {
    initTour();
}

// Start tour when page loads
document.addEventListener('DOMContentLoaded', function() {
    // Check if tour should be shown
    const tourCompleted = localStorage.getItem('amako-tour-completed');
    const urlParams = new URLSearchParams(window.location.search);
    const showTour = urlParams.get('tour') === 'true';
    
    if (showTour || !tourCompleted) {
        setTimeout(() => {
            initTour();
        }, 1000);
    }
});

// Handle window resize
window.addEventListener('resize', function() {
    if (tourActive) {
        showTourStep();
    }
});
</script>

<!-- Static Content (shown when tour is not active) -->
<div id="static-content" class="min-h-screen bg-gradient-to-br from-[#FFF8F0] via-[#FCEDC0] to-white py-8">
    <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <!-- Welcome Header -->
        <div class="text-center mb-12">
            <div class="mb-6 relative">
                <!-- Animated mascot -->
                <div class="text-6xl mb-4 animate-bounce">🥟</div>
                
                <!-- Floating particles around title -->
                <div class="absolute -top-4 -left-4 w-4 h-4 bg-yellow-400 rounded-full animate-ping"></div>
                <div class="absolute -top-4 -right-4 w-3 h-3 bg-pink-400 rounded-full animate-pulse"></div>
                <div class="absolute -bottom-4 -left-8 w-5 h-5 bg-blue-400 rounded-full animate-bounce"></div>
                <div class="absolute -bottom-4 -right-8 w-4 h-4 bg-green-400 rounded-full animate-ping"></div>
                
                <h1 class="text-4xl font-bold text-[#6E0D25] mb-4 relative">
                    Welcome to AmaKo!
                    <!-- Animated underline -->
                    <div class="absolute bottom-0 left-1/2 transform -translate-x-1/2 w-0 h-1 bg-gradient-to-r from-[#6E0D25] to-[#8B0D2F] animate-pulse" style="animation: expandWidth 2s ease-in-out infinite;"></div>
                </h1>
                <p class="text-xl text-gray-600">Your interactive guide to ordering delicious momos</p>
            </div>
            
            <!-- Start Tour Button -->
            <div class="mb-8">
                <button onclick="startAmaKoTour()" class="group relative bg-gradient-to-r from-[#6E0D25] to-[#8B0D2F] text-white px-8 py-4 rounded-xl font-bold text-lg hover:from-[#8B0D2F] hover:to-[#6E0D25] transition-all duration-200 shadow-lg transform hover:scale-105 hover:rotate-1">
                    <span class="relative z-10">🦸‍♂️ Start Interactive Tour</span>
                    <!-- Button glow effect -->
                    <div class="absolute inset-0 bg-gradient-to-r from-[#6E0D25] to-[#8B0D2F] rounded-xl blur opacity-75 group-hover:opacity-100 transition-opacity duration-200"></div>
                </button>
            </div>
        </div>

        <!-- Quick Overview -->
        <div class="bg-white rounded-2xl shadow-lg p-8 mb-8">
            <h2 class="text-2xl font-bold text-[#6E0D25] mb-6 flex items-center">
                <span class="text-3xl mr-3">🎯</span>
                What You'll Learn
            </h2>
            
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                <!-- Interactive Circular Cards -->
                <div class="group relative">
                    <div class="w-48 h-48 mx-auto bg-gradient-to-br from-blue-400 to-blue-600 rounded-full flex items-center justify-center transform transition-all duration-300 hover:scale-110 hover:rotate-3 shadow-lg hover:shadow-2xl cursor-pointer">
                        <div class="text-center text-white">
                            <div class="text-4xl mb-2 group-hover:scale-125 transition-transform duration-300">🛒</div>
                            <h3 class="font-bold text-lg mb-1">How to Order</h3>
                            <p class="text-sm opacity-90">Step-by-step process</p>
                        </div>
                    </div>
                    <!-- Floating particles -->
                    <div class="absolute -top-2 -right-2 w-4 h-4 bg-yellow-400 rounded-full animate-ping"></div>
                    <div class="absolute -bottom-2 -left-2 w-3 h-3 bg-pink-400 rounded-full animate-pulse"></div>
                </div>
                
                <div class="group relative">
                    <div class="w-48 h-48 mx-auto bg-gradient-to-br from-green-400 to-green-600 rounded-full flex items-center justify-center transform transition-all duration-300 hover:scale-110 hover:-rotate-3 shadow-lg hover:shadow-2xl cursor-pointer">
                        <div class="text-center text-white">
                            <div class="text-4xl mb-2 group-hover:scale-125 transition-transform duration-300">📍</div>
                            <h3 class="font-bold text-lg mb-1">Location Setup</h3>
                            <p class="text-sm opacity-90">GPS & delivery</p>
                        </div>
                    </div>
                    <!-- Floating particles -->
                    <div class="absolute -top-2 -left-2 w-4 h-4 bg-blue-400 rounded-full animate-bounce"></div>
                    <div class="absolute -bottom-2 -right-2 w-3 h-3 bg-purple-400 rounded-full animate-ping"></div>
                </div>
                
                <div class="group relative">
                    <div class="w-48 h-48 mx-auto bg-gradient-to-br from-purple-400 to-purple-600 rounded-full flex items-center justify-center transform transition-all duration-300 hover:scale-110 hover:rotate-3 shadow-lg hover:shadow-2xl cursor-pointer">
                        <div class="text-center text-white">
                            <div class="text-4xl mb-2 group-hover:scale-125 transition-transform duration-300">💳</div>
                            <h3 class="font-bold text-lg mb-1">Payment Methods</h3>
                            <p class="text-sm opacity-90">Secure options</p>
                        </div>
                    </div>
                    <!-- Floating particles -->
                    <div class="absolute -top-2 -right-2 w-4 h-4 bg-green-400 rounded-full animate-pulse"></div>
                    <div class="absolute -bottom-2 -left-2 w-3 h-3 bg-yellow-400 rounded-full animate-bounce"></div>
                </div>
                
                <div class="group relative">
                    <div class="w-48 h-48 mx-auto bg-gradient-to-br from-yellow-400 to-yellow-600 rounded-full flex items-center justify-center transform transition-all duration-300 hover:scale-110 hover:-rotate-3 shadow-lg hover:shadow-2xl cursor-pointer">
                        <div class="text-center text-white">
                            <div class="text-4xl mb-2 group-hover:scale-125 transition-transform duration-300">🏆</div>
                            <h3 class="font-bold text-lg mb-1">Rewards Program</h3>
                            <p class="text-sm opacity-90">Points & badges</p>
                        </div>
                    </div>
                    <!-- Floating particles -->
                    <div class="absolute -top-2 -left-2 w-4 h-4 bg-red-400 rounded-full animate-ping"></div>
                    <div class="absolute -bottom-2 -right-2 w-3 h-3 bg-blue-400 rounded-full animate-pulse"></div>
                </div>
                
                <div class="group relative">
                    <div class="w-48 h-48 mx-auto bg-gradient-to-br from-red-400 to-red-600 rounded-full flex items-center justify-center transform transition-all duration-300 hover:scale-110 hover:rotate-3 shadow-lg hover:shadow-2xl cursor-pointer">
                        <div class="text-center text-white">
                            <div class="text-4xl mb-2 group-hover:scale-125 transition-transform duration-300">📱</div>
                            <h3 class="font-bold text-lg mb-1">Order Tracking</h3>
                            <p class="text-sm opacity-90">Real-time updates</p>
                        </div>
                    </div>
                    <!-- Floating particles -->
                    <div class="absolute -top-2 -right-2 w-4 h-4 bg-purple-400 rounded-full animate-bounce"></div>
                    <div class="absolute -bottom-2 -left-2 w-3 h-3 bg-green-400 rounded-full animate-ping"></div>
                </div>
                
                <div class="group relative">
                    <div class="w-48 h-48 mx-auto bg-gradient-to-br from-teal-400 to-teal-600 rounded-full flex items-center justify-center transform transition-all duration-300 hover:scale-110 hover:-rotate-3 shadow-lg hover:shadow-2xl cursor-pointer">
                        <div class="text-center text-white">
                            <div class="text-4xl mb-2 group-hover:scale-125 transition-transform duration-300">🔍</div>
                            <h3 class="font-bold text-lg mb-1">Search & Browse</h3>
                            <p class="text-sm opacity-90">Find items quickly</p>
                        </div>
                    </div>
                    <!-- Floating particles -->
                    <div class="absolute -top-2 -left-2 w-4 h-4 bg-yellow-400 rounded-full animate-pulse"></div>
                    <div class="absolute -bottom-2 -right-2 w-3 h-3 bg-pink-400 rounded-full animate-bounce"></div>
                </div>
            </div>
        </div>

        <!-- Alternative Options -->
        <div class="bg-white rounded-2xl shadow-lg p-8">
            <h2 class="text-2xl font-bold text-[#6E0D25] mb-6 flex items-center">
                <span class="text-3xl mr-3">📖</span>
                Other Resources
            </h2>
            
            <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
                <!-- Interactive Hexagonal Cards -->
                <div class="group relative">
                    <div class="relative w-64 h-64 mx-auto bg-gradient-to-br from-blue-500 to-purple-600 transform transition-all duration-500 hover:scale-110 hover:rotate-6 cursor-pointer" style="clip-path: polygon(50% 0%, 100% 25%, 100% 75%, 50% 100%, 0% 75%, 0% 25%);">
                        <div class="absolute inset-0 bg-gradient-to-br from-blue-400 to-purple-500 opacity-80 group-hover:opacity-100 transition-opacity duration-300" style="clip-path: polygon(50% 0%, 100% 25%, 100% 75%, 50% 100%, 0% 75%, 0% 25%);"></div>
                        <div class="absolute inset-0 flex items-center justify-center text-center text-white">
                            <div>
                                <div class="text-5xl mb-4 group-hover:scale-125 transition-transform duration-300">📚</div>
                                <h3 class="font-bold text-xl mb-2">Detailed Help Guide</h3>
                                <p class="text-sm opacity-90 mb-4">Comprehensive help section</p>
                                <a href="{{ route('help') }}" class="inline-block bg-white text-blue-600 px-6 py-2 rounded-full font-semibold hover:bg-gray-100 transition-all duration-200 transform hover:scale-105">
                                    View Guide
                                </a>
                            </div>
                        </div>
                    </div>
                    <!-- Floating elements -->
                    <div class="absolute -top-4 -right-4 w-6 h-6 bg-yellow-400 rounded-full animate-bounce"></div>
                    <div class="absolute -bottom-4 -left-4 w-4 h-4 bg-pink-400 rounded-full animate-pulse"></div>
                    <div class="absolute top-1/2 -right-8 w-3 h-3 bg-green-400 rounded-full animate-ping"></div>
                </div>
                
                <div class="group relative">
                    <div class="relative w-64 h-64 mx-auto bg-gradient-to-br from-green-500 to-emerald-600 transform transition-all duration-500 hover:scale-110 hover:-rotate-6 cursor-pointer" style="clip-path: polygon(50% 0%, 100% 25%, 100% 75%, 50% 100%, 0% 75%, 0% 25%);">
                        <div class="absolute inset-0 bg-gradient-to-br from-green-400 to-emerald-500 opacity-80 group-hover:opacity-100 transition-opacity duration-300" style="clip-path: polygon(50% 0%, 100% 25%, 100% 75%, 50% 100%, 0% 75%, 0% 25%);"></div>
                        <div class="absolute inset-0 flex items-center justify-center text-center text-white">
                            <div>
                                <div class="text-5xl mb-4 group-hover:scale-125 transition-transform duration-300">🥟</div>
                                <h3 class="font-bold text-xl mb-2">Browse Menu</h3>
                                <p class="text-sm opacity-90 mb-4">Explore delicious menu</p>
                                <a href="{{ route('menu') }}" class="inline-block bg-white text-green-600 px-6 py-2 rounded-full font-semibold hover:bg-gray-100 transition-all duration-200 transform hover:scale-105">
                                    View Menu
                                </a>
                            </div>
                        </div>
                    </div>
                    <!-- Floating elements -->
                    <div class="absolute -top-4 -left-4 w-6 h-6 bg-blue-400 rounded-full animate-pulse"></div>
                    <div class="absolute -bottom-4 -right-4 w-4 h-4 bg-purple-400 rounded-full animate-bounce"></div>
                    <div class="absolute top-1/2 -left-8 w-3 h-3 bg-yellow-400 rounded-full animate-ping"></div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('styles')
<style>
@keyframes expandWidth {
    0% { width: 0; }
    50% { width: 100%; }
    100% { width: 0; }
}

/* Custom hover effects for circular cards */
.group:hover .animate-ping {
    animation-duration: 0.5s;
}

.group:hover .animate-pulse {
    animation-duration: 0.3s;
}

.group:hover .animate-bounce {
    animation-duration: 0.4s;
}

/* Glow effect for hexagonal cards */
.group:hover .bg-gradient-to-br {
    box-shadow: 0 0 30px rgba(59, 130, 246, 0.5);
}

/* Smooth transitions for all interactive elements */
* {
    transition: all 0.3s ease;
}

/* Custom cursor for interactive elements */
.cursor-pointer {
    cursor: pointer;
}

.cursor-pointer:hover {
    cursor: pointer;
}

/* Enhanced floating animations */
@keyframes float {
    0%, 100% { transform: translateY(0px); }
    50% { transform: translateY(-10px); }
}

.animate-float {
    animation: float 3s ease-in-out infinite;
}

/* Pulse glow effect */
@keyframes pulse-glow {
    0%, 100% { box-shadow: 0 0 5px currentColor; }
    50% { box-shadow: 0 0 20px currentColor, 0 0 30px currentColor; }
}

.pulse-glow {
    animation: pulse-glow 2s ease-in-out infinite;
}
</style>
@endpush 